### ISSUE TITLE
some keras issue

### ISSUE THREAD

**Issue by jitendra-n** [rishab-sharma/cnn-hand-written-digit#1]
Using TensorFlow backend.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "build/bdist.linux-x86_64/egg/keras/__init__.py", line 5, in <module>
  File "build/bdist.linux-x86_64/egg/keras/applications/__init__.py", line 8, in <module>
  File "build/bdist.linux-x86_64/egg/keras/applications/mobilenetv2.py", line 77, in <module>
  File "/home/jitendra/.local/lib/python2.7/site-packages/h5py/__init__.py", line 26, in <module>
    from . import _errors
ImportError: cannot import name _errors

**Comment by chinmayshah99** [comment]
Hey @Devil369 there's a similar issue in [SO](https://stackoverflow.com/questions/36375691/python-jupyter-cannot-import-name-errors-for-h5py), check if that helps!

**Comment by cristinaBodnari** [comment]
I got an issue, the css doesn't apply for my web app, I didn't change anything and I have no idea what is happening
